#+TITLE: Backlog for *Xorns* -  an improved way to use Emacs
#+AUTHOR: Merchise Autrement [~ยบ/~]
#+DESCRIPTION: Development planning for this package.

* Backlog for *Xorns*

** Development ideas. [/]

- [ ] Change 'xorns' version to use date-time like most 'elpa' packages.

- [ ] Make a function to remove old versions of installed
  packages in a safe way.

- [ ] Structure 'xorns' in several separate packages using 'Architecture
  Continuum' layers.  Initialization loading order must be imposed, first
  *foundation* and *common systems*; then, in several internal levels of,
  *industry* and *specific* layers.


** Issues [/]

- [ ] Replace 'emacs-goodies-el' with 'elpa'.

- [ ] See [[info:elisp#Warning%20Tips][Tips for Avoiding Compiler Warnings]].

- [ ] Correct error: function not known to be defined ("tramp-connectable-p")
  is used three times in [[file:elpa/xorns-prog.el][xorns-prog.el]], and twice in [[file:elpa/xorns-project.el][xorns-project.el]]


** Configuration. [/]

- [ ] Configure ~ibuffer-saved-filter-groups~ incrementally.

  This is, each module will add its own group.  *xorns-buffers.el* will only
  configure generic modes.

  Plan a similar task for every variable that has parts dependable on specific
  stuffs in different modules.

- [ ] Create a *tagged* configuration system.

  That will allow to determine which features to load in a more precise way.
  See ~xorns-config-level~ function for more information on current actual
  implementation.

  Also, -consider- re-factor setup functions in order to install *xorns*
  features more efficiently and move some of them to be load on demand and not
  in the first configuration.

  Function names could have the pattern ~xorns:setup-<feature-name>~.  Using
  ~xorns:setup~ will configure those features selected in user configuration
  file (currently *Emacs* delays a lot of time in *xorns*) first load.

- [ ] Create ~$HOME/.local/bin/~ symbolic links from [[file:install.el][package installation]].

- [ ] When you 'byte-recompile-directory' elpa, there are two files that must
  not compile, so '.elc' must be erased:

  + requirejs-20151203.2319/snippets/js-mode/.yas-compiled-snippets.el
  + requirejs-20151203.2319/snippets/js2-mode/.yas-compiled-snippets.el

- [ ] There is a package (named 'tide') in our '.emacs.d/elpa/', but don't
  generate 'tide-autoloads' and Emacs reports an error.  This package is not
  used inside any other in 'elpa'.
