#+TITLE: Backlog for *Xorns* -  an improved way to use Emacs
#+AUTHOR: Merchise Autrement [~ยบ/~]
#+DESCRIPTION: Development planning for this package.

* Backlog for *Xorns*

** Development ideas. [/]

- [ ] Change 'xorns' version to use date-time like most 'elpa' packages.

- [ ] Make a function to remove old versions of installed
  packages in a safe way.

- [ ] Structure 'xorns' in several separate packages using 'Architecture
  Continuum' layers.  Initialization loading order must be imposed, first
  *foundation* and *common systems*; then, in several internal levels of,
  *industry* and *specific* layers.


** Minor issues. [/]


** Configuration. [/]

- [ ] Configure ~ibuffer-saved-filter-groups~ incrementally.

  This is, each module will add its own group.  *xorns-buffers.el* will only
  configure generic modes.

  Plan a similar task for every variable that has parts dependable on specific
  stuffs in different modules.

- [ ] Create a *tagged* configuration system.

  That will allow to determine which features to load in a more precise way.
  See ~xorns-config-level~ function for more information on current actual
  implementation.

  Also, -consider- re-factor setup functions in order to install *xorns*
  features more efficiently and move some of them to be load on demand and not
  in the first configuration.

  Function names could have the pattern ~xorns:setup-<feature-name>~.  Using
  ~xorns:setup~ will configure those features selected in user configuration
  file (currently *Emacs* delays a lot of time in *xorns*) first load.
