#!/bin/sh

# author: Medardo Antonio Rodriguez, @med_merchise

# To use this script, cd to your project directory, for example if your
# project is located in "~/work/emacs/xorns" to try xorns on execute:
#
#  $ cd ~/work/emacs/
#  $ source xorns/etc/emacs-venv xorns
#
# All extra-arguments will be used when executing 'emacs' itself.
#
# This script can be copied to any place in your $PATH, for example
# '~/.local/bin' in my case.
#
# It works by simulated a virtual $HOME in '$HOME/.emacs-venvs/', if you need
# some extra $HOME resources, sym-link the original files or directories to
# that target.


if [ -d "$1" ]
then
    PROJECT_NAME=$1
    shift
else
    PROJECT_NAME=`basename $PWD`
    cd ..
fi

if [ -f "$PROJECT_NAME/init.el" ]
then
    WORKON_HOME=$HOME/.emacs-virtualenvs
else
    STATUS=$?
    echo "$PROJECT_NAME is not valid."
    exit $STATUS
fi

if [ -d "$WORKON_HOME" ]
then
    echo "Using work-on home folder: $WORKON_HOME"
else
    echo "Creating work-on home folder: $WORKON_HOME"
    mkdir "$WORKON_HOME"
fi

# Change HOME to local virtual environment
HOME="$WORKON_HOME/$PROJECT_NAME/"

# Creating virtual-env folder
mkdir $HOME/ 2> /dev/null

if [[ -L $HOME/.emacs.d ]]; then rm $HOME/.emacs.d; fi
ln -sf $PWD/$PROJECT_NAME $HOME/.emacs.d

emacs $@
