#+TITLE: Backlog

* Misc

- Check 'obsolete' definitions to remove some.
- Check why =EXWM= has a new "Kill terminal?" prompt.
- Deft is too slow after Emacs 28.  Function =deft-parse-summary= was
  replaced.  Check after Emacs or Deft are updated.
- After configuring 'js2-mode', check ELPA for more packages that use this
  one.
- Check [Use of multi-monitor on EXWM](https://wiki.archlinux.org/title/EXWM)
- Remove =xorns-mail= module (check =xorns-building-blocks=).
- Check =system-packages=, and =use-package-ensure-system-package= for
  =use-package=.
- Change =email= from =med@merchise.org= to =med.merchise@gmail.com=, and
  =date= to =2023=.
- Check why =custom-file= is loaded twice in debug mode (module
  =xorns-config=).
- Upgrade =xorns= to start using =package-vc= after Emacs v29.


* Look for better options to show a System Tray for EXWM

Maybe use the project [py3status](https://github.com/ultrabug/py3status) as a
base to create a similar one named 'exwm-status'.

Note:

  I installed =cbatticon= to show a battery icon.  This program is activated
  by using =sudo systemctl enable cbatticon.service=, because of that, this is
  not needed as part of ~>>=|exwm/startup-applications~.  See
  https://bbs.archlinux.org/viewtopic.php?id=188942

* Fix loss of focus for Brave when using EXWM

It happens when changing the workspace.  Below is an experimental code being
tested:

#+BEGIN_SRC emacs-lisp
  (add-hook
    'exwm-workspace-switch-hook
    (defun >>-workspace-switch ()
      (when (eq exwm-workspace-current-index 2)
        (let* ((frame (selected-frame))
               (buf (current-buffer))
               (win (frame-selected-window frame)) )
          (message ">>= current buffer %s." buf)
          (next-window)
          (switch-to-buffer buf nil 'force)))))

  (setq exwm-workspace-switch-hook '(exwm-systemtray--on-workspace-switch))
#+END_SRC

* Startup error "Symbol's value as variable is void"

Emacs might fail to start with error "Symbol's value as variable is void" if
=file-name-handler-alist= variable is set to nil.  This is done to improve
startup time.  This not happens when option =--without-compress-install= is
not used building Emacs.  We created the =>>-startup-file-name-handler-alist=
function to avoid this in =init.el= file.

See also:
- https://github.com/syl20bnr/spacemacs/issues/11585
- https://mail.gnu.org/archive/html/emacs-devel/2022-08/msg00234.html
