#+TITLE: Backlog

* Misc

- Check 'obsolete' definitions to remove some.
- Check why [[file:~/.emacs.d/elpa/exwm-0.28/exwm.el][EXWM]] has a new "Kill terminal?" prompt.
- Deft is too slow after Emacs 28.  Function =deft-parse-summary= was
  replaced.  Check after Emacs or Deft are updated.
- After configuring 'js2-mode', check ELPA for more packages that use this
  one.
- Check [[https://wiki.archlinux.org/title/EXWM][Use of multi-monitor on EXWM]]
- Remove =xorns-mail= module (check =xorns-building-blocks=).
- Check =system-packages=, and =use-package-ensure-system-package= for
  =use-package=.
- Change =email= from =med@merchise.org= to =med.merchise@gmail.com=, and
  =date= to =2024=.
- Check why =custom-file= is loaded twice in debug mode (module
  =xorns-config=).
- Upgrade =xorns= to start using =package-vc= after Emacs v29.
- Command to kill all =special-mode= buffers, see variables defined in
  =clean-buffer-list=, see also =quit-window= command.
- Create an inverse version of the =quit-window= command to allow configuring
  the =q= key-binding: =(kill-window &optional BURY WINDOW)=.
- Create tools to work with recently opened projects, see [[file:~/.emacs.d/elpa/projectile-20231130.1934/projectile.el::defun projectile-recentf (][projectile]].
- Replace [[help:custom-file][custom-file]] variable to the corresponding function.
- Configure [[file:~/work/emacs/xorns/horns/xorns-exwm.el::defun >>=exwm/enlarge-window-horizontally (&optional delta][exwm-layout]] using a minor mode to resize windows.
- Check [[https://www.emacswiki.org/emacs/awesome-tab.el][awesome-tab]] to configure the [[file:/usr/share/emacs/29.1/lisp/tab-line.el.gz][tab-line]].
- Rename [[file:~/work/emacs/xorns/horns/xorns-window.el::(define-minor-mode >>=window-coach-mode][>>=window-coach-mode]].
- Move [[file:~/work/emacs/xorns/horns/xorns-exwm.el::defun >>-exwm/swap-last-buffers (][>>-exwm/swap-last-buffers]] to module [[file:~/work/emacs/xorns/horns/xorns-window.el][window]].

* Look for better options to show a System Tray for EXWM

Maybe use the project [[https://github.com/ultrabug/py3status][py3status]] as a base to create a similar one named
'exwm-status'.

* Fix loss of focus for Brave when using EXWM

It happens when changing the workspace.  Below is an experimental code being
tested:

#+BEGIN_SRC emacs-lisp
  (add-hook
    'exwm-workspace-switch-hook
    (defun >>-workspace-switch ()
      (when (eq exwm-workspace-current-index 2)
        (let* ((frame (selected-frame))
               (buf (current-buffer))
               (win (frame-selected-window frame)) )
          (message ">>= current buffer %s." buf)
          (next-window)
          (switch-to-buffer buf nil 'force)))))

  (setq exwm-workspace-switch-hook '(exwm-systemtray--on-workspace-switch))
#+END_SRC

* Startup error "Symbol's value as variable is void"

Emacs might fail to start with error "Symbol's value as variable is void" if
=file-name-handler-alist= variable is set to nil.  This is done to improve
startup time.  This not happens when option =--without-compress-install= is
not used building Emacs.  We created the =>>-startup-file-name-handler-alist=
function to avoid this in =init.el= file.

See also:
- https://github.com/syl20bnr/spacemacs/issues/11585
- https://mail.gnu.org/archive/html/emacs-devel/2022-08/msg00234.html

* Integrate Emacs Copilot

- https://github.com/jart/emacs-copilot

* Separate LSP sessions by "some" configuration

Every time a =Python= file is opened it is added to the same =LSP= session.
There would be some problems when simultaneously opening files from different
projects using different versions of Python.

You may need to activate a new =LSP= session.  Temporarily you can call
=lsp-workspace-remove-all-folders= every time you need to switch to a new
workspace.

See command =lsp-describe-session=, and the article "[[https://github.com/emacs-lsp/lsp-mode/discussions/3095][Workspaces in emacs-lsp]]"
for more information.

See [[https://github.com/nex3/perspective-el][Perspective for Emacs]].

* Use browser automation library to create some advanced utilities

The best candidate could be [[https://github.com/microsoft/playwright-python][Playwright]].  See how to [[https://blog.apify.com/unlocking-the-potential-of-brave-and-playwright-for-browser-automation/][use it for brave-browser]].

* Start using [[https://github.com/magnars/expand-region.el][expand-region]]

#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :ensure t
    :bind
    ("C-=" . er/expand-region)
    ("C--" . er/contract-region))
#+END_SRC


* Fix the issue that some UNICODE characters are not displayed

- Install ttf-dejavu and ttf-dejavu-nerd, [[https://superuser.com/questions/13562/how-to-make-unicode-characters-visible-in-emacs][try and set]] "DejaVu Sans Mono" as
  the font.
- Use [[https://github.com/syohex/emacs-fontawesome][fontawesome]] utilities from ELPA.
- Complement [[file:xorns.org::*Prerequisites][related documentation]].

* Redefine configuration of tabs

There must be three modes in the >[[file:~/work/emacs/xorns/horns/xorns-window.el::(defvar >>=|tab-line/initial-mode 'toolbox][>=|tab-line/initial-mode]] variable: (toolbox,
global, and local).  Standard modes should not be mutually exclusive with the
new toolbox mode.

There must be a [[help:tab-line-tabs-function][tab-line-tabs-function]] that is valid for all three modes,
always isolating toolbox buffers from the others.
